### ISSUE TITLE
Cant install Deb Package

### ISSUE THREAD

**Issue by tastech12** [advplyr/audiobookshelf-ppa#3]
I get an error when I try to install any recent .deb package:

apt install /opt/audiobookshelf_1.7.0_amd64.deb
Reading package lists... Error!
E: Invalid archive signature
E: Internal error, could not locate member control.tar{.zst,.lz4,.gz,.xz,.bz2,.lzma,}
E: Could not read meta data from /opt/audiobookshelf_1.7.0_amd64.deb
E: The package lists or status file could not be parsed or opened.

**Comment by tastech12** [comment]
Turns out right clicking on the package in the list at https://github.com/advplyr/audiobookshelf-ppa
results in the following url: https://github.com/advplyr/audiobookshelf-ppa/blob/master/audiobookshelf_1.7.0_amd64.deb

If I click on that entry the get the link from the download button i get:
https://github.com/advplyr/audiobookshelf-ppa/raw/master/audiobookshelf_1.7.0_amd64.deb

Only the second link works.

**Comment by advplyr** [comment]
Thanks for the heads up
