### ISSUE TITLE
nstall Audiobookshelf on Debian 11

### ISSUE THREAD

**Issue by witzker** [advplyr/audiobookshelf-ppa#4]
Hi,
I'm new with this server stuff
I installed the [Turkey Core ISO](https://www.turnkeylinux.org/core) on esxi7

Then I followed the instructions from here
https://www.audiobookshelf.org/install
`
wget https://advplyr.github.io/audiobookshelf-ppa/audiobookshelf_2.2.1_amd64.deb
sudo apt install ./audiobookshelf_2.2.1_amd64.deb

but did not work

The i tried to install the package
audiobookshelf_2.2.1_amd64.deb in Webmin
![grafik](https://user-images.githubusercontent.com/4120266/195996283-cc7e3a5c-4dff-4ff6-9155-ac62d0a51c5d.png)

![grafik](https://user-images.githubusercontent.com/4120266/195996298-5e084032-5415-46d5-99c6-7c2205d4b4b4.png)

and get this:

2022-10-14 20:48:42 (7.16 MB/s) - 'ffmpeg-git-amd64-static.tar.xz.12' saved [40997632/40997632]

tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
dpkg: error processing archive /root/audiobookshelf_2.2.1_amd64.deb (--install):
new audiobookshelf package pre-installation script subprocess returned error exit status 2
Errors were encountered while processing:
/root/audiobookshelf_2.2.1_amd64.deb

Pls Help a newbie to get this installed
THX

**Comment by advplyr** [comment]
The debian package only supports AMD64 architecture. I'm not familiar with your system

**Comment by witzker** [comment]
THX for clearing!
Ups I have not noticed it!
My server is a tiny dell:
![image](https://user-images.githubusercontent.com/4120266/196004953-32dc3b62-f56a-4808-bdb5-ea252b88c59e.png)
What package is suitable?
I don't want to use Docker!
Pls. Advice

**Comment by advplyr** [comment]
You will need to use Docker. It is much easier then what you are trying to do I'm sure and runs on every OS.
Is there a particular reason you don't want to use Docker or is it just the learning curve?

**Comment by witzker** [comment]
_or is it just the learning curve?_

Yes, I'm totally new with this server stuff and want to understand what's going on. (at least try)
Docker is absolutely new and strange at the moment, so what are my possibilities on ESXi 7
THX

**Comment by advplyr** [comment]
I don't know what ESXi 7 is. There are 2 options to install audiobookshelf right now, the debian package and docker. It seems your system is not supporting the debian package so that leaves you with docker.
If you can set up a VM then you can setup Docker.

**Comment by advplyr** [comment]
I suggest you join the discord server and someone may be able to help you there. This doesn't appear to be a bug with the debian package.

**Comment by codhopper** [comment]
> tar (child): xz: Cannot exec: No such file or directory 

You should be able to fix with `apt install xz-utils` as your install of debian is minimal. `xz` is used by tar to compress/decompress files in a similar way to gzip or bzip (more common). 

**To note:** ESXi is a fairly popular hypervisor from VMWare and it sounds like a regular debian 11 x86_64 (amd64) virtual machine is running.

**Comment by witzker** [comment]
> VMWare and it sounds like a regular debian 11 x86_64 (amd64) virtual machine is running.

Yes, I hope I installed this:
https://www.turnkeylinux.org/core

**Comment by witzker** [comment]
WORX THX

**Now the next Problem:**
I want to make a library from a Folder on my Synology.
Tried several things but no result
What do I have to set Here:
![image](https://user-images.githubusercontent.com/4120266/197895291-7d1b482a-c523-4a3f-ac92-b96cc26651de.png)

The folder on my Synology looks like this:
![image](https://user-images.githubusercontent.com/4120266/197895393-b23be9d3-5248-42da-97a2-df4939deff51.png)

Do I have to mount the path first on Debian ?
If yes, where to.

Pls. help

**Comment by advplyr** [comment]
the library name will be whatever you want.
then you need to enter the exact path to the folder where it says "New folder path"

The Browse button is not going to work well in debian.

For assistance on these I recommend checking out the discord server.

**Comment by witzker** [comment]
THX for taking care
Pls.help updating to the latest version
Not Docker 
I'm on Debian and cannot find instructions
